name: checkblock00
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ready to Go
      run: |
        python3 -m pip install -U pip
        mkdir -p ~/.config/PyFunceble
        pip3 install setuptools
        pip3 install wheel
        pip3 install pyfunceble
        rm -f dest/deadblock00
        cp PyFunceble.yaml ~/.config/PyFunceble/.PyFunceble.yaml
        python3 checkblock00.py
        git config --global user.email "72325061+anti-ad-bot@users.noreply.github.com"
        git config --global user.name "anti-ad-bot"
        git add dest/deadblock00
        git commit -am "update file dest/deadblock00"

    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REB_TOKEN }}
        branch: 'master'
