name: prepare src
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: download anti-AD domains file
      run: |
        curl --connect-timeout 60 -s -o - https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt | grep -v '#' | split -l 1500 -a 2 -x - splitblock
        mv -f splitblock* ./src/
        git config --global user.email "72325061+anti-ad-bot@users.noreply.github.com"
        git config --global user.name "anti-ad-bot"
        git add ./src/*
        git commit -am "prepare src files."

    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REB_TOKEN }}
        branch: 'master'
